jitsi-multitrack-recorder {
  recording {
    directory = "/tmp"
    // Supported formats: "mka", "json"
    format = "mka"
    // The maximum duration of a gap to repair using Opus PLC.
    max-gap-duration = 5 minutes
    enabled = true
  }
  log-finalize-output = true
  // finalize-script = /path/to/finalize.sh
  port = 8989

  deepgram {
    enabled = false
    api-key = ""
    model = "nova-2"
  }
}
