jitsi-multitrack-recorder {
  recording {
    directory = "/tmp"
    // Supported formats: "mka", "mka"
    format = "mka"
    // The maximum duration of a gap to repair using Opus PLC.
    max-gap-duration = 5 minutes
  }
  log-finalize-output = true
  // finalize-script = /path/to/finalize.sh
  port = 8989

  live-forward {
    enabled = false
    url = ""
    auth-token = ""
    recording-enabled = false
    send-start-events = true
    send-audio-events = true
    fail-on-forward-error = false
    max-queue-size = 10000
  }
}
